<a href="https://colab.research.google.com/github/romanowiczadam/ml_course/blob/master/01_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.1_Import_bibliotek

In [2]:
import numpy as np
import pandas as pd
import sklearn

sklearn.__version__

'0.22.2.post1'

1.2_Generowanie_danych

In [5]:
data = {
    'size' : ['XL', 'L', 'M', 'L', 'M'],
    'color' : ['red', 'green', 'blue', 'green', 'red'],
    'gender' : ['female', 'male', 'male', 'female', 'female'],
    'price' : [199.0, 89.0, 99.0, 129.0, 79.0],
    'weight' : [500, 450, 300, 380, 410],
    'bought' : ['yes', 'no', 'yes', 'no', 'yes'],
}
print(data)

df_raw = pd.DataFrame(data=data)
print(df_raw)

{'size': ['XL', 'L', 'M', 'L', 'M'], 'color': ['red', 'green', 'blue', 'green', 'red'], 'gender': ['female', 'male', 'male', 'female', 'female'], 'price': [199.0, 89.0, 99.0, 129.0, 79.0], 'weight': [500, 450, 300, 380, 410], 'bought': ['yes', 'no', 'yes', 'no', 'yes']}
  size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M    red  female   79.0     410    yes


1.3_Utworzenie_kopii_danych

In [8]:
df_r = df_raw.copy()
df_r.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   size    5 non-null      object 
 1   color   5 non-null      object 
 2   gender  5 non-null      object 
 3   price   5 non-null      float64
 4   weight  5 non-null      int64  
 5   bought  5 non-null      object 
dtypes: float64(1), int64(1), object(4)
memory usage: 368.0+ bytes


1.4_Zmiana_typu_danych_oraz_wstępna_eksploaracja

In [11]:
for col in ['size', 'color', 'gender', 'bought']:
  df_r[col] = df_r[col].astype('category')

df_r['weight'] = df_r['weight'].astype('float')

df_r.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   size    5 non-null      category
 1   color   5 non-null      category
 2   gender  5 non-null      category
 3   price   5 non-null      float64 
 4   weight  5 non-null      float64 
 5   bought  5 non-null      category
dtypes: category(4), float64(2)
memory usage: 628.0 bytes


In [12]:
df_r.describe()

price      weight
count    5.000000    5.000000
mean   119.000000  408.000000
std     48.476799   75.299402
min     79.000000  300.000000
25%     89.000000  380.000000
50%     99.000000  410.000000
75%    129.000000  450.000000
max    199.000000  500.000000

In [13]:
df_r.describe().T

count   mean        std    min    25%    50%    75%    max
price     5.0  119.0  48.476799   79.0   89.0   99.0  129.0  199.0
weight    5.0  408.0  75.299402  300.0  380.0  410.0  450.0  500.0

In [15]:
# aby uwględnione były również zmienne category
df_r.describe(include = ['category']).T

count unique     top freq
size       5      3       M    2
color      5      3     red    2
gender     5      2  female    3
bought     5      2     yes    3

In [16]:
df_r

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue    male   99.0   300.0    yes
3    L  green  female  129.0   380.0     no
4    M    red  female   79.0   410.0    yes

1.5_LabelEncoder

In [35]:
# LabelEncoder używa sie raczej do target
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
le.fit(df_r['bought'])
le.transform(df_r['bought'])

# można użyć tych dwóch metod od razu:
#le.fit_transform(df['bought'])

array([1, 0, 1, 0, 1])

In [36]:
# wyswietlenie jak wyglada mapowianie
le.classes_

array(['no', 'yes'], dtype=object)

In [37]:
df_r['bought'] = le.fit_transform(df_r['bought'])
df_r

size  color  gender  price  weight  bought
0   XL    red  female  199.0   500.0       1
1    L  green    male   89.0   450.0       0
2    M   blue    male   99.0   300.0       1
3    L  green  female  129.0   380.0       0
4    M    red  female   79.0   410.0       1

In [0]:
# aby wrócić
df_r['bought'] = le.inverse_transform(df_r['bought'])

1.6_OneHotEncoder

In [39]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse = False)
encoder.fit(df_r[['size']])

# dzieki temu, że sparse = False możemy podejrzec macierz

OneHotEncoder(categories='auto', drop=None, dtype=<class 'numpy.float64'>,
              handle_unknown='error', sparse=False)

In [40]:
encoder.transform(df_r[['size']])

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [41]:
encoder.categories_

[array(['L', 'M', 'XL'], dtype=object)]

In [42]:
# parametr drop= 'first' usuwa pierwsza kolumne tak by nie popełnic
# 'bledu kodowania zero- jedynkowego'
encoder = OneHotEncoder(drop = 'first', sparse = False)
encoder.fit_transform(df_r[['size']])

array([[0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.]])

In [43]:
df_r

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue    male   99.0   300.0    yes
3    L  green  female  129.0   380.0     no
4    M    red  female   79.0   410.0    yes

1.7_Get_dummies()-Pandas

In [44]:
pd.get_dummies(data = df_r)

price  weight  size_L  ...  gender_male  bought_no  bought_yes
0  199.0   500.0       0  ...            0          0           1
1   89.0   450.0       1  ...            1          1           0
2   99.0   300.0       0  ...            1          0           1
3  129.0   380.0       1  ...            0          1           0
4   79.0   410.0       0  ...            0          0           1

[5 rows x 12 columns]

In [45]:
pd.get_dummies(data = df_r, drop_first = True)

price  weight  size_M  ...  color_red  gender_male  bought_yes
0  199.0   500.0       0  ...          1            0           1
1   89.0   450.0       0  ...          0            1           0
2   99.0   300.0       1  ...          0            1           1
3  129.0   380.0       0  ...          0            0           0
4   79.0   410.0       1  ...          1            0           1

[5 rows x 8 columns]

In [46]:
pd.get_dummies(data = df_r, drop_first = True, prefix = 'new')

price  weight  new_M  new_XL  new_green  new_red  new_male  new_yes
0  199.0   500.0      0       1          0        1         0        1
1   89.0   450.0      0       0          1        0         1        0
2   99.0   300.0      1       0          0        0         1        1
3  129.0   380.0      0       0          1        0         0        0
4   79.0   410.0      1       0          0        1         0        1

In [47]:
pd.get_dummies(data = df_r, drop_first = True, prefix_sep = '-')

price  weight  size-M  ...  color-red  gender-male  bought-yes
0  199.0   500.0       0  ...          1            0           1
1   89.0   450.0       0  ...          0            1           0
2   99.0   300.0       1  ...          0            1           1
3  129.0   380.0       0  ...          0            0           0
4   79.0   410.0       1  ...          1            0           1

[5 rows x 8 columns]

In [48]:
# zastosowanie kodowania tylko dla wybranych kolumn
pd.get_dummies(data = df_r, drop_first = True, columns=['size'])

color  gender  price  weight bought  size_M  size_XL
0    red  female  199.0   500.0    yes       0        1
1  green    male   89.0   450.0     no       0        0
2   blue    male   99.0   300.0    yes       1        0
3  green  female  129.0   380.0     no       0        0
4    red  female   79.0   410.0    yes       1        0

1.8_Standaryzacja-StandarScaler

In [54]:
# std() pandas - nieobciążony
# std() numpy - obicążony
print(df_r['price'])
print(df_r['price'].mean())
print(df_r['price'].std())

0    199.0
1     89.0
2     99.0
3    129.0
4     79.0
Name: price, dtype: float64
119.0
48.47679857416329


In [55]:
 # standaryzacja
( df_r['price'] - df_r['price'].mean() ) / df_r['price'].std()

0    1.650274
1   -0.618853
2   -0.412568
3    0.206284
4   -0.825137
Name: price, dtype: float64

In [56]:
# funkcja
def standarize(x):
  return  ( x - x.mean() )/ x.std() 

standarize(df_r['price'])

0    1.650274
1   -0.618853
2   -0.412568
3    0.206284
4   -0.825137
Name: price, dtype: float64

In [58]:
# funkcja z sklearn
from sklearn.preprocessing import scale

scale(df_r['price'])

array([ 1.84506242, -0.69189841, -0.4612656 ,  0.2306328 , -0.92253121])

In [60]:
# jednak poleca używac tej funkcji
from sklearn.preprocessing import StandardScaler
# tworzymy instancje klasy
scaler = StandardScaler()
scaler.fit(df_r[['price']])
scaler.transform(df_r[['price']])

array([[ 1.84506242],
       [-0.69189841],
       [-0.4612656 ],
       [ 0.2306328 ],
       [-0.92253121]])

In [0]:
# jednoczesne standaryzowanie wszystkich danych numerycznych
scaler = StandardScaler()
df_r[['price', 'weight']] = scaler.fit_transform(df_r[['price', 'weight']])

In [63]:
df_r

size  color  gender     price    weight bought
0   XL    red  female  1.845062  1.366002    yes
1    L  green    male -0.691898  0.623610     no
2    M   blue    male -0.461266 -1.603567    yes
3    L  green  female  0.230633 -0.415740     no
4    M    red  female -0.922531  0.029696    yes

1.9_Przygotowanie_danych_do_modelu

In [64]:
# powrot do dancyh surowych
df = df_raw.copy()
df

size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M    red  female   79.0     410    yes

In [65]:
# 1.target

le = LabelEncoder()
df['bought'] = le.fit_transform(df['bought'])

# 2.standaryzacja

scaler = StandardScaler()
df[['price', 'weight']] = scaler.fit_transform(df[['price', 'weight']])

# 3.Zmiana danych tektowych

df = pd.get_dummies(data=df, drop_first = True)
df


price    weight  bought  ...  color_green  color_red  gender_male
0  1.845062  1.366002       1  ...            0          1            0
1 -0.691898  0.623610       0  ...            1          0            1
2 -0.461266 -1.603567       1  ...            0          0            1
3  0.230633 -0.415740       0  ...            1          0            0
4 -0.922531  0.029696       1  ...            0          1            0

[5 rows x 8 columns]