<a href="https://colab.research.google.com/github/romanowiczadam/ml_course/blob/master/06_gradient_descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import plotly.express as px

np.random.seed(42)

In [43]:
X1 = np.array([1,2,3,4,5,6])
Y = np.array([3000, 3250, 3500, 3750, 4000, 4250])
m = len(X1)
print(X1)
print(Y)



[1 2 3 4 5 6]
[3000 3250 3500 3750 4000 4250]


In [44]:
X1 = X1.reshape(m,1)
Y = Y.reshape(-1,1)
print(X1)
print(Y)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[3000]
 [3250]
 [3500]
 [3750]
 [4000]
 [4250]]


In [45]:
o = np.ones([m,1])
X_1 = np.append(o, X1, axis = 1)
print(X_1.shape)
X_1

(6, 2)


array([[1., 1.],
       [1., 2.],
       [1., 3.],
       [1., 4.],
       [1., 5.],
       [1., 6.]])

In [54]:
# wskaźnik uczenia
eta = 0.01

weights = np.random.randn(2, 1)
print(X_1)
# te liczby są naszym poczatkowym w0 i w1 
print(weights)

[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]]
[[ 0.24196227]
 [-1.91328024]]


Metoda gradientu prostego

In [55]:
# tworzymy dwie listy
# bedziemy do nich dodawac wartosci naszego w0 
intercept = []
# oraz w1
coef = []

# wyznaczamy gradient (wzór z wykładu)
for i in range(3000):
  gradient = (2/m) * X_1.T.dot(X_1.dot(weights) - Y)
  weights = weights - eta * gradient
  intercept.append(weights[0][0])
  coef.append(weights[1][0])

print(weights)
print(intercept)



[[2749.95601151]
 [ 250.01027481]]
[72.87105264326075, 125.22478817212402, 163.7741329852377, 192.92142738924383, 215.66169344747186, 234.0325318149187, 249.42019380120237, 262.76780712480354, 274.7170352476723, 285.70445050250123, 296.0270982838132, 305.8871014235814, 315.4220052668267, 324.7254219157619, 333.86107484206343, 342.8723536632924, 351.78881441167493, 360.6306017721399, 369.4114576025743, 378.1407676791007, 386.82495413034724, 395.4684227333984, 404.0742073749777, 412.64440848925733, 421.1804913346491, 429.6834889167934, 438.1541400408206, 446.59298323100944, 455.0004206263229, 463.37676145004883, 471.72225158337267, 480.03709368523005, 488.3214608806396, 496.57550607356734, 504.7993682830877, 512.9931769544439, 521.157054892398, 529.2911202573001, 537.3954879235094, 545.4702704040109, 553.5155784799061, 561.5315216291239, 569.5182083185347, 577.4757462031354, 585.4042422620101, 593.3038028912785, 601.1745339677776, 609.0165408928356, 616.8299286224957, 624.614801688524, 6

Wizualizacja dopasowania

In [56]:
df = pd.DataFrame(data = {'i' : intercept, 'c': coef})
df

i           c
0       72.871053  266.983477
1      125.224788  449.230849
2      163.774133  572.531756
3      192.921427  655.732934
4      215.661693  711.656111
...           ...         ...
2995  2749.955363  250.010426
2996  2749.955526  250.010388
2997  2749.955689  250.010350
2998  2749.955850  250.010312
2999  2749.956012  250.010275

[3000 rows x 2 columns]

In [62]:
px.line(df, y = 'i', width=600, title = 'Dopasowanie: intercept')

In [63]:
px.line(df, y = 'c', width= 600, title = 'Dopasowanie : coef')